version: '3.8'

services:
  app:
    container_name: node-express-app
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=mysecret
      - DB_NAME=testdb
      - NODE_ENV=development

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mysecret
      MARIADB_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: